### ISSUE TITLE
Break action function into subfunction

### ISSUE THREAD

**Issue by vanh17** [vanh17/hc07-Obedient#26]
#### Breaking down the action function
- [x] function that handles trigger #27 
- [x] function that handles basic movements #33
- [x] function that direct to right forward/backward/turnleft/turnright upon word recognized #34 
- [x] function that handles forward with numeric values #28
- [x] function that handles backward with numeric values #29
- [x] function that handles turn left with numeric values #30
- [x] function that handles turn right with numeric values #31
